apiVersion: v1
kind: Service
metadata:
  name: {{ include "kxi-helm-charts.fullname" . }}
  labels:
    app: {{ include "kxi-helm-charts.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "kxi-helm-charts.name" . }}
